### ISSUE TITLE
Test query math occasionally fails

### ISSUE THREAD

**Issue by fritzo** [priorknowledge/loom#42]
<pre>
======================================================================
FAIL: loom.test.test_query_math.test_samples_match_scores_one('mixed-10-10-0.5',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fobermeyer/.virtualenvs/sf/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/fobermeyer/sf/loom/loom/test/util.py", line 59, in test_one
    fun(**kwargs)
  File "/home/fobermeyer/sf/loom/loom/test/test_query_math.py", line 159, in test_samples_match_scores_one
    _check_marginal_samples_match_scores(protobuf_server, row, 0)
  File "/home/fobermeyer/sf/loom/loom/test/test_query_math.py", line 149, in _check_marginal_samples_match_scores
    assert_greater(gof, MIN_GOODNESS_OF_FIT)
AssertionError: 0.00044184774310638907 not greater than 0.001
--------------------  begin captured stdout  ---------------------
    Prob    Count
   0.944      282 ------------------------------------------------------------
   0.056       18 ----
    Prob    Count
   0.938      271 ------------------------------------------------------------
   0.062       29 ------
</pre>

**Comment by fritzo** [comment]
@jglidden-salesforce @jglidden did you already fix this?

**Comment by jglidden** [comment]
Yes I fixed it by making the test parameters less stringent (to match the
posterior enumeration tests)

**Comment by fritzo** [comment]
Still fails:

<pre>
======================================================================
FAIL: loom.test.test_query_math.test_samples_match_scores('mixed-10-10-0.5',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fritz/.virtualenvs/sf/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/fritz/sf/loom/loom/test/util.py", line 60, in test_one
    fun(**kwargs)
  File "/home/fritz/sf/loom/loom/test/test_query_math.py", line 125, in test_samples_match_scores
    _check_marginal_samples_match_scores(server, row, 0)
  File "/home/fritz/sf/loom/loom/test/test_query_math.py", line 116, in _check_marginal_samples_match_scores
    assert_greater(gof, MIN_GOODNESS_OF_FIT)
AssertionError: 1.3714409179932956e-06 not greater than 0.0001
-------------------- begin captured stdout ---------------------
    Prob    Count
   0.657      326 ------------------------------------------------------------
   0.342      174 --------------------------------
    Prob    Count
   0.639      317 ------------------------------------------------------------
   0.361      183 -----------------------------------
    Prob    Count
   0.636      318 ------------------------------------------------------------
   0.363      182 ----------------------------------
    Prob    Count
   0.632      354 ------------------------------------------------------------
   0.363      146 -------------------------
---------------------  end captured stdout  ----------------------
</pre>

**Comment by fritzo** [comment]
@jglidden still fails

**Comment by fritzo** [comment]
<pre>
======================================================================
FAIL: loom.test.test_query_math.test_entropy('gp-10-10-0.5',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/priorknowledge/loom/loom/test/util.py", line 61, in test_one
    fun(**kwargs)
  File "/home/travis/build/priorknowledge/loom/loom/test/test_query_math.py", line 108, in test_entropy
    _test_entropy(name, sample_count=1000)
  File "/home/travis/build/priorknowledge/loom/loom/test/test_query_math.py", line 135, in _test_entropy
    assert_estimate_close(cpp_estimate, py_estimate)
  File "/home/travis/build/priorknowledge/loom/loom/test/test_query_math.py", line 142, in assert_estimate_close
    assert_less(abs(log(actual.variance / expected.variance)), 1.0)
AssertionError: nan not less than 1.0
--------------------  begin captured stdout  ---------------------
41.3153991699 41.1044104538 0.0221577528864 0.0203582431034
32.2428894043 32.1851114616 0.0106941061094 0.0117722069328
19.2287483215 19.2913250771 0.00602774322033 0.00680452016605
40.6672859192 40.3987246823 0.0196710675955 0.0175170641454
0.0 0.0 0.0 0.0
---------------------  end captured stdout  ----------------------
----------------------------------------------------------------------
Ran 631 tests in 503.664s
FAILED (SKIP=1, failures=1)
make[1]: *** [test] Error 1
make[1]: Leaving directory `/home/travis/build/priorknowledge/loom'
make: *** [small-test] Error 2
travis_time:end:15a8ef8e:start=1415304203846262364,finish=1415304755810699509,duration=551964437145
[0K
[31;1mThe command "NOSE_PROCESSES=0 make small-test" exited with 2.[0m
Done. Your build exited with 1.
</pre>
